config/routes.rb
Rails.application.routes.draw do
  get 'fish-api/exams', to: 'fish_api#exams', as: :fish_api_exams
  get 'fish-api/users', to: 'fish_api#users', as: :fish_api_users
  get 'maintenance/maintenance', to: 'maintenance#maintenance', as: :maintenance
  get '/status', to: 'home#status', as: :status

  #INDICATORS
  get 'indicators/repeated-exams', to: 'indicators#repeated_exams_report', as: :repeated_exams_report
  get 'indicators/global_production', to: 'indicators#global_production', as: :global_production
  get 'indicators/production_per_stand/:stand', to: 'indicators#production_per_stand', as: :production_per_stand
  get "indicators/response_time/:group", to: "indicators#response_time", as: :response_time
  get 'indicators/health_ensurances_relation', to: 'indicators#health_ensurances_relation', as: :health_ensurances_relation
  get 'indicators/concluded_exams', to: 'indicators#concluded_exams', as: :concluded_exams
  get 'indicators/exams_in_progress', to: 'indicators#exams_in_progress', as: :exams_in_progress

  # EXAMS
  patch "exams/:id/reopen", to: "exams#reopen_exam", as: :reopen_exam
  patch "exams/:id/remove-report", to: 'exams#remove_report', as: :remove_report
  patch 'exams/:id/partial_released', to: 'exams#change_to_partial_released', as: :partial_released
  get 'exams/:id/partial_released', to: 'exams#partial_released', as: :change_to_partial_released
  patch 'exams/:id/save_report', to: 'exams#save_exam_report', as: :save_exam_report
  get 'exams/:id/add_report', to: 'exams#add_report', as: :add_report_to_exam
  patch 'exams/:id', to: 'exams#update', as: :update_exam
  patch 'exams/:id/initiate', to: 'exams#initiate', as: :initiate_exam
  patch 'exams/:id/completed', to: 'exams#completed', as: :change_to_completed
  patch 'exams/:id/change_exam_status', to: 'exams#change_exam_status', as: :change_exam_status
  get 'exams/:id/edit', to: 'exams#edit', as: :edit_exam
  get 'exams/:id/start', to: 'exams#start', as: :start_exam
  get 'attendance/:id/exams/new', to: 'exams#new', as: :new_exam
  post 'attendance/:id/exams/new', to: 'exams#create', as: :create_exam

  root 'home#index'
  post 'home/longin', to: 'home#login'
  post 'home/logout', to: 'home#logout'
  get 'home', to: 'home#logged_in', as: :home
  resources :brands
  resources :samples
  resources :releases
  resources :products
  resources :hospitals
  resources :work_maps
  resources :subsamples
  resources :suggestions
  resources :offered_exams
  resources :stock_entries
  resources :stock_products
  resources :users, except: [:show]
  resources :patients, except: [:destroy]
  resources :backups, only: [:index, :show, :create]
  resources :stock_outs, only: [:index, :new, :create]
  resources :attendances, except: [:delete, :index, :edit]
  resources :internal_codes, only: [:create, :destroy, :index]
end

app/views/layouts/user_dropdowns/_hospital.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="hospital-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Hospital
  </a>
  <div class="dropdown-menu" aria-labelledby="hospital-dropdown">
    <%= link_to 'Novo', new_hospital_path, {class: 'dropdown-item', id: 'new-hospital'} %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Todos', hospitals_path, {class: 'dropdown-item', id: 'hospitals'} %>
  </div>
</li>

app/views/layouts/user_dropdowns/_offered_exams.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="offered-exam-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Exames
  </a>
  <div class="dropdown-menu" aria-labelledby="offered-exam-dropdown">
    <%= link_to 'Novo', new_offered_exam_path, class: 'dropdown-item', id: 'new-offered-exam' %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Buscar', offered_exams_path, class: 'dropdown-item', id: 'offered-exams' %>
  </div>
</li>

app/views/layouts/user_dropdowns/_patient.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="patient-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Paciente
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to 'Novo', new_patient_path, {class: 'dropdown-item', id: 'new-patient'} %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Buscar', patients_path, {class: 'dropdown-item', id: 'patients'} %>
  </div>
</li>

app/views/layouts/user_dropdowns/_samples.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="samples-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Amostras
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to 'Imunofenotipagem', internal_codes_path(field: :imunofeno), class: 'dropdown-item', id: 'samples-imunofeno' %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Biologia Molecular', internal_codes_path(field: :biomol), class: 'dropdown-item', id: 'samples-biomol' %>
    <div class="dropdown-divider"></div>
    <%= link_to 'FISH', internal_codes_path(field: :fish), class: 'dropdown-item', id: 'samples-fish' %>
  </div>
</li>

app/views/layouts/user_dropdowns/_suggestions.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="suggestions-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Funcionalidades
    <%= bedge Suggestion.from_user(current_user).in_line.size, :light %>
    <%= bedge Suggestion.from_user(current_user).development.size, :info %>
    <%= bedge Suggestion.from_user(current_user).waiting_validation.size, :primary%>
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to 'Nova funcionalidade', new_suggestion_path(kind: "new_feature"), class: 'dropdown-item', id: 'new-feature' %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Reportar bug', new_suggestion_path(kind: "bug_report"), class: 'dropdown-item', id: 'bug-report' %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Melhoria', new_suggestion_path(kind: "feature_improvement"), class: 'dropdown-item', id: 'new-improvement' %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Minhas solicitações', suggestions_path(from_user: true), class: 'dropdown-item', id: 'suggestions-user' %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Solicitados', suggestions_path, class: 'dropdown-item', id: 'suggestions' %>
  </div>
</li>

app/views/layouts/user_dropdowns/_work_map.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="work-map-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Mapas de trabalho
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to 'Novo', new_work_map_path, class: 'dropdown-item', id: 'new-work-map' %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Buscar', work_maps_path, class: 'dropdown-item', id: 'work-maps' %>
  </div>
</li>