config/routes.rb
Rails.application.routes.draw do
  get 'fish-api/exams', to: 'fish_api#exams', as: :fish_api_exams
  get 'fish-api/users', to: 'fish_api#users', as: :fish_api_users
  get 'maintenance/maintenance', to: 'maintenance#maintenance', as: :maintenance
  get '/status', to: 'home#status', as: :status

  #INDICATORS
  get 'indicators/repeated-exams', to: 'indicators#repeated_exams_report', as: :repeated_exams_report
  get 'indicators/global_production', to: 'indicators#global_production', as: :global_production
  get 'indicators/production_per_stand/:stand', to: 'indicators#production_per_stand', as: :production_per_stand
  get "indicators/response_time/:group", to: "indicators#response_time", as: :response_time
  get 'indicators/health_ensurances_relation', to: 'indicators#health_ensurances_relation', as: :health_ensurances_relation
  get 'indicators/concluded_exams', to: 'indicators#concluded_exams', as: :concluded_exams
  get 'indicators/exams_in_progress', to: 'indicators#exams_in_progress', as: :exams_in_progress

  # EXAMS
  patch "exams/:id/reopen", to: "exams#reopen_exam", as: :reopen_exam
  patch "exams/:id/remove-report", to: 'exams#remove_report', as: :remove_report
  patch 'exams/:id/partial_released', to: 'exams#change_to_partial_released', as: :partial_released
  get 'exams/:id/partial_released', to: 'exams#partial_released', as: :change_to_partial_released
  patch 'exams/:id/save_report', to: 'exams#save_exam_report', as: :save_exam_report
  get 'exams/:id/add_report', to: 'exams#add_report', as: :add_report_to_exam
  patch 'exams/:id', to: 'exams#update', as: :update_exam
  patch 'exams/:id/initiate', to: 'exams#initiate', as: :initiate_exam
  patch 'exams/:id/completed', to: 'exams#completed', as: :change_to_completed
  patch 'exams/:id/change_exam_status', to: 'exams#change_exam_status', as: :change_exam_status
  get 'exams/:id/edit', to: 'exams#edit', as: :edit_exam
  get 'exams/:id/start', to: 'exams#start', as: :start_exam
  get 'attendance/:id/exams/new', to: 'exams#new', as: :new_exam
  post 'attendance/:id/exams/new', to: 'exams#create', as: :create_exam

  root 'home#index'
  post 'home/longin', to: 'home#login'
  post 'home/logout', to: 'home#logout'
  get 'home', to: 'home#logged_in', as: :home
  resources :brands
  resources :samples
  resources :releases
  resources :products
  resources :hospitals
  resources :work_maps
  resources :subsamples
  resources :suggestions
  resources :offered_exams
  resources :stock_entries
  resources :stock_products
  resources :users, except: [:show]
  resources :patients, except: [:destroy]
  resources :backups, only: [:index, :show, :create]
  resources :stock_outs, only: [:index, :new, :create]
  resources :attendances, except: [:delete, :index, :edit]
  resources :internal_codes, only: [:create, :destroy, :index]
end

app/views/layouts/admin_navbar_dropdowns/_hospitals.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="hospital-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Hospital
  </a>
  <div class="dropdown-menu" aria-labelledby="hospital-dropdown">
    <%= link_to 'Novo', new_hospital_path, {class: 'dropdown-item', id: 'new-hospital'} %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Buscar', hospitals_path, {class: 'dropdown-item', id: 'hospitals'} %>
  </div>
</li>

app/views/layouts/admin_navbar_dropdowns/_offered_exam.html.erb
<li class="nav-item dropdown">
	<a class="nav-link dropdown-toggle" href="#" id="offered-exam-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		Exame
	</a>
	<div class="dropdown-menu" aria-labelledby="offered-exam-dropdown">
		<%= link_to 'Novo', new_offered_exam_path, {class: 'dropdown-item', id: 'new-offered-exam'} %>
		<div class="dropdown-divider"></div>
		<%= link_to 'Buscar', offered_exams_path, {class: 'dropdown-item', id: 'offered-exams'} %>
	</div>
</li>

app/views/layouts/admin_navbar_dropdowns/_suggestions.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="suggestion-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Funcionalidades <%= bedge Suggestion.todo.size, :dark %>
  </a>
  <div class="dropdown-menu" aria-labelledby="user-dropdown">
    <%= link_to suggestions_path(kind: 'in_progress'), class: 'dropdown-item', id: 'suggestions-in-progress' do %>
      Em desenvolvimento <%= bedge Suggestion.in_progress.size, :info %>
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to suggestions_path(kind: 'in_line'), class: 'dropdown-item', id: 'suggestions-in-line' do %>
      Na fila
      <%= bedge Suggestion.in_line.where(kind: :new_feature).size, :primary %>
      <%= bedge Suggestion.in_line.where(kind: :bug_report).size, :danger %>
      <%= bedge Suggestion.in_line.where(kind: :feature_improvement).size, :info %>
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to suggestions_path(kind: 'complete'), {class: 'dropdown-item', id: 'suggestions-complete'} do %>
      Concluídos <%= bedge Suggestion.complete.size, :success %>
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Todos', suggestions_path, {class: 'dropdown-item', id: 'all-suggestions'} %>
  </div>
</li>

app/views/layouts/admin_navbar_dropdowns/_user.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="user-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Usuário
  </a>
  <div class="dropdown-menu" aria-labelledby="user-dropdown">
    <%= link_to 'Novo', new_user_path, {class: 'dropdown-item', id: 'new-user'} %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Usuários', users_path({kind: 'user'}), {class: 'dropdown-item', id: 'users'} %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Administradores', users_path({kind: 'admin'}), {class: 'dropdown-item', id: 'admins'} %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Todos', users_path, {class: 'dropdown-item', id: 'all-users'} %>
  </div>
</li>

app/views/layouts/admin_navbar_dropdowns/_vertions.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="release-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Versões
  </a>
  <div class="dropdown-menu" aria-labelledby="release-dropdown">
    <%= link_to 'Novo', new_release_path, {class: 'dropdown-item', id: 'new-release'} %>
    <div class="dropdown-divider"></div>
    <%= link_to 'Versões', releases_path, {class: 'dropdown-item', id: 'releases'} %>
  </div>
</li>