config/routes.rb
Rails.application.routes.draw do
  get 'fish-api/exams', to: 'fish_api#exams', as: :fish_api_exams
  get 'fish-api/users', to: 'fish_api#users', as: :fish_api_users
  get 'maintenance/maintenance', to: 'maintenance#maintenance', as: :maintenance
  get '/status', to: 'home#status', as: :status

  #INDICATORS
  get 'indicators/repeated-exams', to: 'indicators#repeated_exams_report', as: :repeated_exams_report
  get 'indicators/global_production', to: 'indicators#global_production', as: :global_production
  get 'indicators/production_per_stand/:stand', to: 'indicators#production_per_stand', as: :production_per_stand
  get "indicators/response_time/:group", to: "indicators#response_time", as: :response_time
  get 'indicators/health_ensurances_relation', to: 'indicators#health_ensurances_relation', as: :health_ensurances_relation
  get 'indicators/concluded_exams', to: 'indicators#concluded_exams', as: :concluded_exams
  get 'indicators/exams_in_progress', to: 'indicators#exams_in_progress', as: :exams_in_progress

  # EXAMS
  patch "exams/:id/reopen", to: "exams#reopen_exam", as: :reopen_exam
  patch "exams/:id/remove-report", to: 'exams#remove_report', as: :remove_report
  patch 'exams/:id/partial_released', to: 'exams#change_to_partial_released', as: :partial_released
  get 'exams/:id/partial_released', to: 'exams#partial_released', as: :change_to_partial_released
  patch 'exams/:id/save_report', to: 'exams#save_exam_report', as: :save_exam_report
  get 'exams/:id/add_report', to: 'exams#add_report', as: :add_report_to_exam
  patch 'exams/:id', to: 'exams#update', as: :update_exam
  patch 'exams/:id/initiate', to: 'exams#initiate', as: :initiate_exam
  patch 'exams/:id/completed', to: 'exams#completed', as: :change_to_completed
  patch 'exams/:id/change_exam_status', to: 'exams#change_exam_status', as: :change_exam_status
  get 'exams/:id/edit', to: 'exams#edit', as: :edit_exam
  get 'exams/:id/start', to: 'exams#start', as: :start_exam
  get 'attendance/:id/exams/new', to: 'exams#new', as: :new_exam
  post 'attendance/:id/exams/new', to: 'exams#create', as: :create_exam

  root 'home#index'
  post 'home/longin', to: 'home#login'
  post 'home/logout', to: 'home#logout'
  get 'home', to: 'home#logged_in', as: :home
  resources :brands
  resources :samples
  resources :releases
  resources :products
  resources :hospitals
  resources :work_maps
  resources :subsamples
  resources :suggestions
  resources :offered_exams
  resources :stock_entries
  resources :stock_products
  resources :users, except: [:show]
  resources :patients, except: [:destroy]
  resources :backups, only: [:index, :show, :create]
  resources :stock_outs, only: [:index, :new, :create]
  resources :attendances, except: [:delete, :index, :edit]
  resources :internal_codes, only: [:create, :destroy, :index]
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  validates_presence_of :offered_exam, :status
  belongs_to :offered_exam
  belongs_to :attendance
  has_many :exam_status_changes
  before_validation :default_values
  has_and_belongs_to_many :internal_codes
  has_attached_file :report
  validates_attachment_content_type :report, :content_type => ["application/pdf"]
  has_attached_file :partial_released_report
  #validates_attachment_content_type :partial_released_report, :content_type => ["application/pdf"]
  after_create :reload_issues_cache
  after_update :reload_issues_cache
  before_update :treat_two_internal_codes_case
  enum status: {
    progress: 1,
    tecnical_released: 2,
    in_repeat: 3,
    complete: 4,
    waiting_start: 5,
    partial_released: 6,
    complete_without_report: 7,
    canceled: 8
  }

  def self.status_name status
    I18n.t "enums.exam.status.#{status}"
  end

  def change_status user_id
    ExamStatusChange.create({
      new_status: self.status,
      exam: self,
      change_date: DateTime.now,
      user_id: user_id
    })
    self.save
  end

  def reopen user_id
    self.report = nil
    self.status = :progress
    attendance = self.attendance
    attendance.reopen if attendance.complete?
    self.change_status user_id
  end

  def is_late?
    days_took = ValidDaysCounterService.new(self.created_at.to_date, Date.current).call
    days_took > self.offered_exam.refference_date
  end

  def verify_if_was_late
    refference_date = self.offered_exam.refference_date
    days_took = ValidDaysCounterService.new(self.created_at.to_date, self.finish_date).call
    if days_took > refference_date
      self.was_late = true
      self.lag_time = days_took - refference_date
    end
  end

  def self.from_field field
    self.joins(:offered_exam).where("offered_exams.field_id = ?", field.id)
  end

  def self.complete
    self.where(status: :complete)
  end

  def self.waiting_start
    self.where(status: :waiting_start)
  end

  def self.progress
    self.where.not(status: [:complete, :canceled])
  end

  def self.not_canceled
    self.where.not(status: :canceled)
  end

  def status_name
    I18n.t("enums.exam.status.#{self.status}")
  end

  private

    def default_values
    	self.status = :waiting_start unless self.status
      self.was_late = false unless self.was_late
      self.lag_time = 0 unless  self.lag_time
    end

    def reload_issues_cache
      self.offered_exam.field.set_issues_in_cache
    end

    def treat_two_internal_codes_case
      compose_internal_codes = ComposeInternalCodeGeneratorService.new(self).call
      self.internal_codes = compose_internal_codes if compose_internal_codes
    end

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  include ChangeExamStatus
  include InstanceVariableSetter
  before_action :set_exam, only: [
                                  :initiate,
                                  :change_exam_status,
                                  :start,
                                  :completed,
                                  :edit,
                                  :update,
                                  :partial_released,
                                  :remove_report,
                                  :add_report,
                                  :change_to_partial_released,
                                  :save_exam_report,
                                  :reopen_exam
                                ]
  before_action :set_internal_codes, only: [:start, :edit]
  before_action :user_filter
  before_action :set_offered_exams, only: [:new, :edit]
  before_action :set_fields, only: [:new, :exams_from_patient]

  def new
    @exam = Exam.new(attendance_id: params[:id])
  end

  def create
    @exam = Exam.new(exam_params)
    if @exam.save
      flash[:success] = I18n.t :new_exam_success
    else
      flash[:warning] = @exam.errors.full_messages.first
    end
    redirect_to_exams_tab
  end

	def start
	end

	def edit
	end

	def update
    if @exam.update(exam_params)
			flash[:success] = I18n.t :edit_exam_success
		else
      flash[:warning] = @exam.errors.full_messages.first
		end
    redirect_to_exams_tab
	end

  # GET exams/1/partial_released
  def partial_released
  end

  # GET exams/1/add_report
  def add_report
  end

  # PATCH exams/1/save_exam_report
  def save_exam_report
    @exam.status = :complete
    if @exam.update exam_params
      flash[:success] = I18n.t :add_report_to_exam_success
      redirect_to_exams_tab
    else
      redirect_to add_report_path(@exam)
    end
  end

  def remove_report
    if params[:kind] == "partial_released"
      if @exam.update({status: :progress, partial_released_report: nil})
        flash[:success] = I18n.t :remove_report_success
      else
        flash[:error] = @exam.erros.complete_message.first
      end
    end
    redirect_to_exams_tab
  end

  def reopen_exam
    if @exam.reopen session[:user_id]
      flash[:success] = I18n.t :exam_reopen_success
    else
      flash[:error] = @exam.errors.full_messages.first
    end
    redirect_to_exams_tab
  end

  private

  	def exam_params
			params.require(:exam).permit(
        :offered_exam_id,
        :attendance,
        :internal_code_ids,
        :report,
        :partial_released_report,
        :attendance_id,
      )
  	end

    def set_exam
      @exam = Exam.includes(:offered_exam, :attendance).find params[:id]
    end

		def set_internal_codes
      internal_codes = @exam.attendance.internal_codes
      unless @exam.offered_exam.field == Field.BIOMOL
        @internal_codes = internal_codes
        return
      else
        internal_codes = internal_codes.joins(:subsample)
      end
			dna = internal_codes.where("subsamples.subsample_kind_id = ?", SubsampleKind.DNA.id).first
      rna = internal_codes.where("subsamples.subsample_kind_id = ?", SubsampleKind.RNA.id).first
      if dna && rna
        internal_code =  InternalCode.new(code: "#{dna.code}  -  #{rna.code}", id: nil)
        internal_codes = internal_codes.to_a << internal_code
      end
      @internal_codes = internal_codes
		end

    def set_offered_exams
      @offered_exams = OfferedExam
                                  .where(is_active: true)
                                  .where(field: session[:field_id])
                                  .order(name: :asc)
    end

    def redirect_to_exams_tab
      redirect_to attendance_path(@exam.attendance, {tab: "exams"})
    end

end

app/helpers/exams_helper.rb
module ExamsHelper

  COLOR = {
    waiting_start: :dark,
    progress: :primary,
    in_repeat: :warning,
    complete_without_report: :info,
    partial_released: :secondary,
    complete: :success,
    canceled: :danger,
  }

  def show_exam_status status
    %Q(<span class="text-#{COLOR[status.to_sym]}">#{Exam.status_name(status)}</span>).html_safe
  end

  def exam_options_helper exam
    @exam = exam
    options = ""
    return "".html_safe if @exam.canceled?
    is_in_progress = @exam.complete_without_report? == false && @exam.complete? == false
    if @exam.waiting_start?
      options << start_exam_link
      options << edit_link
    elsif is_in_progress
      options << in_progress_options
      options << edit_link
    elsif  @exam.complete_without_report?
      options << add_report_link
    else
      options << complete_options
    end
    options << cancel_exam_link unless @exam.complete?
    options.html_safe
  end

  private

    def tecnical_released_link
      link = ""
      unless @exam.tecnical_released?
        link = link(
          @exam,
          new_status: :tecnical_released,
          css_class: 'secondary change-to-tecnical-released'
        )
      end
      link
    end

    def in_repeat_link
      link = ""
      unless @exam.in_repeat?
        link = link(
          @exam,
          new_status: :in_repeat,
          css_class: 'warning change-to-in-repeat'
        )
      end
      link
    end

    def start_exam_link
      link_to(
        'Iniciar exame',
        start_exam_path(@exam),
        id: 'start-exam',
        class: 'btn btn-sm btn-outline-primary ml-3 start-exam'
        )
    end

    def partial_released_link
      link_to(
        'Liberado parcial',
        change_to_partial_released_path(@exam),
        class: 'btn btn-sm btn-outline-info ml-3 change-to-partial-released'
        )
    end

    def complete_link
      link = ""
      unless @exam.complete? || @exam.complete_without_report?
        link = link_to(
          'Concluído',
          change_to_completed_path(@exam),
          data: { confirm: "Tem certeza ?" },
          method: :patch,
          class: 'btn btn-sm btn-outline-success ml-3 change-to-complete'
          )
      end
      link
    end

    def link(exam, new_status: nil, css_class: "", method: "patch")
      link_to(
        Exam.status_name(new_status),
        change_exam_status_path(exam, {new_status: new_status}),
        method: method,
        class: "btn btn-sm ml-3 btn-outline-#{css_class}"
      )
    end

    def edit_link
      link_to(
        'Editar',
        edit_exam_path(@exam),
        class: 'btn btn-sm btn-warning ml-2 edit-exam'
      )
    end

    def add_report_link
      link_to(
        'Adicionar laudo',
        add_report_to_exam_path(@exam),
        class: 'ml-3 add-report'
        )
    end

    def in_progress_options
      options = ""
      options << tecnical_released_link
      options << in_repeat_link
      options << partial_released_link
      options << complete_link
      options
    end

    def cancel_exam_link
      link_to(
        "Cancelar",
        change_exam_status_path(@exam, {new_status: :canceled}),
        data: { confirm: "Tem certeza ?" },
        method: :patch,
        class: "btn btn-sm btn-outline-danger cancel-exam ml-3"
      )
    end

    def complete_options
      options = ""
      options << "<label class = 'text-success ml-3'>Exame concluído</label>".html_safe
      options << link_to(
        'Visualizar laudo',
        add_report_to_exam_path(@exam),
        class: 'btn btn-sm btn-info see-report ml-3'
        )
      options << link_to(
        "Reabrir exame",
        reopen_exam_path(@exam),
        method: :patch,
        data: { confirm: "Tem certeza ?" },
        class: 'btn btn-sm btn-outline-danger ml-3 reopen-exam'
      )
      options
    end

end

app/views/exams/add_report.html.erb
<%= render 'layouts/user_navbar' %>

<div class="col-md-12 pl-4 pr-4 mt-3">

  <div class="col-md-5 d-inline-block offset-md-1 border-right">
    <h5 class="text-center">
      Paciente: <%= link_to @exam.attendance.patient.name, patient_path(@exam.attendance.patient), id: 'patient-link' %>
    </h5>
  </div>

  <div class="col-md-5 d-inline-block">
    <h5 class="text-center">
      Atendimento:
      <span id='lis-code'>
        <%= @exam.attendance.lis_code %>
      </span>
    </h5>
  </div>
</div>

<hr>

<div class="card mt-5 col-md-8 offset-md-2 p-0">
  <div class="card-header bg-info">
    <h4 class="text-center text-white">
      <%= @exam.offered_exam.name %>
    </h4>
  </div>
  <div class="card-body">

    <%= form_with(model: @exam, url: save_exam_report_path(@exam), method: :patch, multipart: true, class: 'form-inline') do |f| %>

      <div id="error_explanation">
        <ul>
          <% @exam.errors.full_messages.each do |message| %>
            <li class="error"><%= message %></li>
          <% end %>
        </ul>
      </div>

      <div class='form-group'>
        <label class='h3'>Selecione um arquivo: </label>
        <%= f.file_field :report, class: '', required: true %>
        <button id="btn-save" class='btn btn-outline-primary'>
          Salvar
        </button>
      </div>
    <% end %>

    <% unless @exam.report? %>
      <h3 class="text-center text-secondary mt-5">
        Nenhum laudo adicionado.
      </h3>
    <% else %>
      <embed src="<%= @exam.report.url %>" height="1150" class = 'offset-md-1 col-md-10 mt-5' />
    <% end %>
  </div>
</div>

app/views/exams/edit.html.erb
<%= render 'layouts/user_navbar' %>

<div class="card col-md-10 offset-md-1 mt-5 p-0">
  <div class="card-header">
  	<h3 class="text-center">
    	Editar exame
  	</h3>
  </div>
  <div class="card-body">
    <%= form_for(@exam, {url: update_exam_path , method: :patch}) do |f| %>

			<div class = 'form-group'>
				<%= f.label :offered_exam %>
        <%= f.select :offered_exam_id, options_from_collection_for_select(@offered_exams, "id", "name", selected: @exam.offered_exam.id), {}, class: 'form-control' %>
			</div>

      <% unless @exam.internal_codes.empty? %>
  			<div class = 'form-group'>
  				<%= f.label "Código da amostra" %>
          <% if @exam.internal_codes.size == 2 %>
            <%= f.select :internal_code_ids, options_from_collection_for_select(@internal_codes, 'id', 'code', selected: @internal_codes.last.id), {}, {class: 'form-control'} %>
          <% else %>
            <%= f.select :internal_code_ids, options_from_collection_for_select(@internal_codes, 'id', 'code', selected: @exam.internal_codes.first.id), {}, {class: 'form-control'} %>
          <% end %>
        </div>
      <% end %>

			<button id="btn-save" class='btn btn-outline-primary float-right'>
				Salvar
			</button>

		<% end %>
  </div>

</div>

<script>

  let has_two_internal_codes = <%= @exam.internal_codes.size %> === 2
  if (has_two_internal_codes)
    $("#exam_internal_code_ids option:last").attr("selected", "selected")

</script>

app/views/exams/exams_from_patient.html.erb
<%= render 'layouts/user_navbar' %>
<div class="col-md-6 offset-md-3 mt-3" style="overflow: auto;">
  <%= form_with(url: exams_from_patient_path(@patient), method: :get) do |form| %>
    <div class="form-group">
      <%= form.label Field.model_name.human %>
      <%= form.select :field_id, content_tag(:option,'Todos',:value=>"0") + options_from_collection_for_select(@fields, "id", "name"), {}, class: 'form-control' %>
    </div>
    <button class="btn btn-outline-info float-right">
      Buscar
    </button>
  <% end %>
</div>

<hr class="mt-3 mb-3">

<h3 class="text-center">
  <%= @patient.name %>
</h3>

<table class="table table-bordered text-center col-md-10 offset-md-1">
  <thead class="bg-dark text-white">
    <th>Exame</th>
    <th>Área</th>
    <th>Data de início</th>
    <th>Status</th>
    <th>Atendimento (Lis)</th>
  </thead>
  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td>
          <%= exam.offered_exam.name %>
        </td>
        <td>
          <%= exam.offered_exam.field.name %>
        </td>
        <td>
          <% unless exam.start_date.nil? %>
            <%= l exam.start_date %>
          <% else %>
            -
          <% end %>
        </td>
        <td>
          <%= show_exam_status exam.status %>
        </td>
        <td>
          <%= link_to exam.attendance.lis_code, workflow_path(exam.attendance, tab: :exams) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/exams/new.html.erb
<%= render 'layouts/user_navbar' %>

<div class="card col-md-8 offset-md-2 p-0 mt-5">
  <div class="card-header bg-info">
    <h3 class="text-center text-white">
      Novo exame
    </h3>
  </div>
  <div class="card-body">
    <div>
      <%= form_with model: @exam, url: create_exam_path(@exam.attendance) do |form| %>
        <%= form.text_field :attendance_id, value: @exam.attendance_id, hidden: true, id: "exam_attendance_id" %>

        <div class="form-group">
          <label>Área</label>
          <%= select_tag "field", options_from_collection_for_select(@fields, "id", "name"), class: 'form-control', id: 'field_select', name: 'field' %>
        </div>
        <div class="form-group">
          <label for="">Exame</label>
          <select id="exam_select" class="form-control" name="exam[offered_exam_id]">
            <% @offered_exams.each do |offered_exam|%>
              <option value="<%=offered_exam.id%>" class="exam-option">
                <%= offered_exam.name %>
              </option>
            <% end %>
          </select>
        </div>
        <button id="btn-save" class="btn btn-outline-primary float-right">
          Salvar
        </button>
      <% end %>
    </div>
  </div>
</div>

<script>
  $("#field_select").val("<%= session[:field_id]%>")
</script>

<script>
  $('#field_select').change(() => {
    let options = $('.exam-option')
    options.remove()
    const field_id = $('#field_select').val()
    axios.get(`/offered_exams/field/${field_id}`)
      .then(response => {
        const exams = response.data
        exams.forEach(exam => {
          $('#exam_select').append(`
              <option value="${exam.id}" class="exam-option">
                ${exam.name}
              </option>
            `)
        })
      })
      .catch(() => alert('Houve um erro no servidor, tente novamente mais tarde.'))
  })
</script>

app/views/exams/partial_released.html.erb
<%= render 'layouts/user_navbar' %>

<div class="card mt-5 col-md-8 offset-md-2 p-0">
  <div class="card-header bg-info">
    <h3 class="text-center text-white">
      Liberado parcial
    </h3>
  </div>
  <div class="card-body">
    <div style="overflow: auto;">
      <%= form_with model: @exam, url: partial_released_path(@exam) do |form| %>

        <div class="form-group">
          <label class='h3'>Selecione um arquivo com o laudo: </label><br>
          <%= form.file_field :partial_released_report, required: true %>
        </div>
        <button id="btn-save" class='btn btn-outline-primary float-right'>
          Salvar
        </button>

      <% end %>
    </div>

    <hr>

    <% unless @exam.partial_released_report? %>
      <h3 class="text-center text-secondary mt-5">
        Nenhum laudo adicionado.
      </h3>
    <% else %>
      <embed src="<%= @exam.partial_released_report.url %>" height="1150" class = 'offset-md-1 col-md-10 mt-5' />
    <% end %>

  </div>

</div>

app/views/exams/start.html.erb
<%= render 'layouts/user_navbar' %>

<div class="card col-md-10 offset-md-1 mt-5 p-0">
  <div class="card-header bg-info">
  	<h3 class="text-white text-center">
    	Iniciar exame
  	</h3>
  </div>
  <div class="card-body">
    <%= form_for(@exam, {url:  initiate_exam_url , method: :patch}) do |f| %>

			<div class = 'form-group'>
				<%= f.label :offered_exam %>
				<%= f.text_field :offered_exam, value: @exam.offered_exam.name, disabled: true, class: 'form-control', id: 'exam-name' %>
			</div>

      <% if @internal_codes.size > 0 %>

  			<div class = 'form-group'>
  				<%= f.label "Amostra" %>
  				<% f.select :internal_code_ids, options_from_collection_for_select(@internal_codes, 'id', 'code'), {}, {class: 'form-control'} %>
          <select class="form-control" name="exam[internal_codes]" id="sample_select">
            <% @internal_codes.each do |internal_code| %>
              <option class = "internal-code-option" value="<%= internal_code.id %>">
                <% unless internal_code.sample.nil? %>
                  <%= "#{internal_code.code} - #{internal_code.sample.sample_kind.name}" %>
                <% else %>
                  <%= "#{internal_code.code}" %>
                <% end %>
              </option>
            <% end %>
          </select>
        </div>

  			<button class='btn btn-outline-primary float-right' id="btn-save">
  				Salvar
  			</button>

      <% else %>
        <h5 id="without-sample" class="text-center text-danger">
          Nenhum código interno da <%= @exam.offered_exam.field.name %> encontrado para este atentimento.
        </h5>
      <% end %>

		<% end %>
  </div>

</div>